-- AlterTable
ALTER TABLE "Category" ALTER COLUMN "image" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Customer" ALTER COLUMN "offers" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Service" ALTER COLUMN "noOfComments" DROP NOT NULL,
ALTER COLUMN "rating" DROP NOT NULL;

-- AlterTable
ALTER TABLE "Vendor" ALTER COLUMN "avi" DROP NOT NULL,
ALTER COLUMN "cover" DROP NOT NULL;
